create table pages
(
    id  bigint generated by default as identity
        constraint pages_pkey
            primary key,
    url varchar(255)
        constraint uk_j62tu7ktcxqexai58m799i0wa
            unique
);