create table words
(
    id          bigint generated by default as identity
        constraint words_pkey
            primary key,
    occurrences integer not null,
    word        varchar(255),
    page_id     bigint
        constraint fk9rlebn4i8vb1mdyglgrs41csa
            references pages
);